name: CI
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      test-chunks: ${{ steps.setTestChunks.outputs.TEST_CHUNKS }}
      test-chunk-ids: ${{ steps.setTestChunksIds.outputs.TEST_CHUNK_IDS }}
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - id: setTestChunks
        name: Set Chunks
        run: echo "TEST_CHUNKS=$(npx jest --listTests --json | jq -cM '[_nwise(length / 2 | floor)]')" >> "$GITHUB_OUTPUT"
      - id: setTestChunksIds
        name: Set Chunk IDs
        run: echo "TEST_CHUNK_IDS=$(echo $CHUNKS | jq -cM 'to_entries | map(.key)')" >> "$GITHUB_OUTPUT"
        env:
          CHUNKS: ${{ steps.setTestChunks.outputs.TEST_CHUNKS }}
  test:
    runs-on: ubuntu-latest
    name: test (chunk ${{ matrix.chunk }})
    needs:
      - setup
    strategy:
      matrix:
        chunk: ${{ fromJson(needs.setup.outputs.test-chunk-ids) }}
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - name: jest
        run: echo $CHUNKS | jq '.[${{ matrix.chunk }}] | .[] | @text' | xargs npx jest
        env:
          CHUNKS: ${{ needs.setup.outputs.test-chunks }}
